name: lightweight-api 
description: Lightweight rest API to serve filler database.

secrets:
  api_port:
    description: Port for api
    default: 3000

services:
  api:
    build:
      context: .
    interfaces:
      main:
        port: ${{ secrets.api_port }}
        ingress:
          subdomain: api
    environment:
      PORT: ${{ secrets.api_port }}
    debug:
      command: npm run dev
      build:
        args:
          NODE_ENV: development
      volumes:
        src:
          mount_path: /usr/src/app/src
          host_path: ./src
